name: .NET Core

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup LocalDB
      run: SqlLocalDb create DndDdd
    - name: Start LocalDB
      run: SqlLocalDb start DndDdd
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Stop LocalDB
      run: SqlLocalDb stop DndDdd
    - name: Remove LocalDB instance
      run: SqlLocalDb delete DndDdd
